### ISSUE TITLE
Graylog refused to connect

### ISSUE THREAD

**Issue by nokia88** [lephisto/pfsense-analytics#1]
I followed the steps in the README.md file but i got stuck when accessing the Graylog webURL.
The browser error message is "refused to connect" while the URL for Cerebro and Grafana works fine.

docker-compose.yml
`GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/`

```
sudo netstat -tulpn | grep 9000

sudo netstat -tulpn | grep 3000
tcp6       0      0 :::3000                 :::*                    LISTEN      14130/docker-proxy

sudo netstat -tulpn | grep 9001
tcp6       0      0 :::9001                 :::*                    LISTEN      14170/docker-proxy
```

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

```
sudo ufw status
Status: inactive
```

**Comment by markinho1970** [comment]
Any thing about this??

**Comment by lephisto** [comment]
Is the Graylog container running? Paste "docker ps" pls.

**Comment by markinho1970** [comment]
Now, I installed without docker... and working now... Thanks...

**Comment by themendas** [comment]
When starting the GrayLog container it gives me an error:

ERROR: org.graylog2.bootstrap.CmdLineTool - Invalid configuration


Este seria el log de arranque:
2020-12-31 18:49:31,519 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: AWS plugins 3.1.4 [org.graylog.aws.AWSPlugin]
2020-12-31 18:49:31,533 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Collector 3.1.4 [org.graylog.plugins.collector.CollectorPlugin]
2020-12-31 18:49:31,542 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Threat Intelligence Plugin 3.1.4 [org.graylog.plugins.threatintel.ThreatIntelPlugin]
2020-12-31 18:49:31,700 ERROR: org.graylog2.bootstrap.CmdLineTool - Invalid configuration
com.github.joschi.jadconfig.ValidationException: The minimum length for "password_secret" is 16 characters.
        at org.graylog2.Configuration.validatePasswordSecret(Configuration.java:288) ~[graylog.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
        at com.github.joschi.jadconfig.ReflectionUtils.invokeMethodsWithAnnotation(ReflectionUtils.java:53) ~[graylog.jar:?]
        at com.github.joschi.jadconfig.JadConfig.invokeValidatorMethods(JadConfig.java:221) ~[graylog.jar:?]
        at com.github.joschi.jadconfig.JadConfig.process(JadConfig.java:100) ~[graylog.jar:?]
        at org.graylog2.bootstrap.CmdLineTool.processConfiguration(CmdLineTool.java:351) [graylog.jar:?]
        at org.graylog2.bootstrap.CmdLineTool.readConfiguration(CmdLineTool.java:344) [graylog.jar:?]
        at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:178) [graylog.jar:?]
        at org.graylog2.bootstrap.Main.main(Main.java:50) [graylog.jar:?]

Y este seria la configuración que he modificado:

# CHANGE ME (must be at least 16 characters)!
GRAYLOG_PASSWORD_SECRET=********
# Password: admin
GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
GRAYLOG_HTTP_EXTERNAL_URI=http://publicIP:9000/
# TZ List - https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
GRAYLOG_TIMEZONE=Europe/Madrid
