### ISSUE TITLE
Can't connect to mongodb

### ISSUE THREAD

**Issue by thale13** [lephisto/pfsense-analytics#33]
So, I had everything working and then had some hardware problems.  After resolving them, things wouldn't start cleanly.  I didn't know if it was something I did or not, so I burned all the containers and started from scratch (CENTOS 8 vm, not rebuilt, only the docker stuff was).

Now, as before, graylog can't connect to mongo.  All I get is this:
raylog_1        | 2020-06-23 13:23:35,123 INFO : org.mongodb.driver.cluster - Cluster description not yet available. Waiting for 30000 ms before timing out
graylog_1        | 2020-06-23 13:23:36,172 INFO : org.mongodb.driver.cluster - Exception in monitor thread while connecting to server mongo:27017
graylog_1        | com.mongodb.MongoSocketOpenException: Exception opening socket
graylog_1        | 	at com.mongodb.connection.SocketStream.open(SocketStream.java:62) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:126) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:114) [graylog.jar:?]
graylog_1        | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
graylog_1        | Caused by: java.net.NoRouteToHostException: No route to host (Host unreachable)
graylog_1        | 	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_232]
graylog_1        | 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_232]
graylog_1        | 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_232]
graylog_1        | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_232]
graylog_1        | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_232]
graylog_1        | 	at java.net.Socket.connect(Socket.java:607) ~[?:1.8.0_232]
graylog_1        | 	at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:59) ~[graylog.jar:?]
graylog_1        | 	at com.mongodb.connection.SocketStream.open(SocketStream.java:57) ~[graylog.jar:?]
graylog_1        | 	... 3 more
graylog_1        | 2020-06-23 13:24:05,124 ERROR: org.graylog2.bindings.providers.MongoConnectionProvider - Error connecting to MongoDB: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=mongo:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.NoRouteToHostException: No route to host (Host unreachable)}}]
graylog_1        | 2020-06-23 13:24:05,144 INFO : org.graylog2.shared.buffers.InputBufferImpl - Message journal is enabled.

and it doesn't start right.  Grafana also errors out with an message about not connecting to download the pie-chart plugin.  Elasticsearch and Cerebro start fine, as far as I can tell.

Any ideas?
T.

**Comment by thale13** [comment]
Ok, so firewalld seems to be my problem.  BUT, I had to stop docker, then stop the firewall, then start docker.  Now things seem to be running.  At least I'm further.

Stupid firewall....

**Comment by thale13** [comment]
Graylog login prompt achieved.....
